In [1]:
from grapycal_audio_torch.dataset import PianoRollDataset
from torch.utils.data import DataLoader, Dataset
import torch

device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [2]:
from grapycal_audio.pianoroll import PianoRoll

def tokenize(pr:PianoRoll, n_velocity=128, duration:int|None=None, seq_len:int|None=None):
    tokens = []
    frame = 0
    if duration is None:
        duration = pr.duration

    tokens.append({'type':'start', 'frame':frame})
    for note in pr.notes:
        if note.onset > duration:
            break
        while note.onset > frame:
            tokens.append({'type':'next_frame', 'frame':frame})
            frame += 1
        
        tokens.append({'type':'pitch', 'frame':frame, 'value':note.pitch-21})
        tokens.append({'type':'velocity', 'frame':frame, 'value':int(note.velocity*(n_velocity/128))})

    while duration > frame:
        tokens.append({'type':'next_frame', 'frame':frame})
        frame += 1

    # fill in the next_frame
    for i in range(len(tokens)-1):
        tokens[i]['next_frame'] = tokens[i+1]['frame']

    tokens.pop() # remove the last next_frame 128

    # we're using seq_len+1 because start token doesn't count
    if seq_len is not None:
        tokens = tokens[:seq_len+1]

        if len(tokens) < seq_len+1:
            tokens += [{'type':'pad'}] * (seq_len+1 - len(tokens))

    return tokens

In [3]:
def binary_positional_encoding(length:int, dim:int):
    res = []
    for i in range(length):
        res.append([int(x) for x in f"{i:0{dim}b}"])
        # pad
        res[-1] += [0] * (dim - len(res[-1])) 

    return (
        torch.tensor(res, dtype=torch.float32)
    )
    
def sinusoidal_positional_encoding(length:int, dim:int):
    res = []
    for d in range(dim // 2):
        res.append(torch.sin(torch.arange(length) / 10000 ** (2 * d / dim)))
    for d in range(dim // 2):
        res.append(torch.cos(torch.arange(length) / 10000 ** (2 * d / dim)))
    return torch.stack(res, dim=1)

def construct_input_frame(token:dict, pos_encoding:torch.Tensor, n_pitch, n_velocity, frame_bias:int = 0):

    if token['type'] == 'pad':
        return torch.zeros(n_pitch + n_velocity + 2 + pos_encoding.shape[1] * 2 )

    #pitch
    pitch = torch.zeros(n_pitch)
    if token['type'] == 'pitch':
        pitch[token['value']] = 1

    #velocity
    velocity = torch.zeros(n_velocity)
    if token['type'] == 'velocity':
        velocity[token['value']] = 1

    #next_frame
    next_frame = torch.zeros(1)
    if token['type'] == 'next_frame':
        next_frame[0] = 1
    
    #start
    start = torch.zeros(1)
    if token['type'] == 'start':
        start[0] = 1

    #pos
    pos = pos_encoding[token['frame']-frame_bias]

    #target pos
    target_pos = pos_encoding[token['next_frame']-frame_bias]
    

    return torch.cat([pitch, velocity, next_frame, start, pos, target_pos], dim=0)

def construct_input_tensor(tokens, pos_encoding:torch.Tensor, n_pitch, n_velocity, frame_bias:int = 0):

    frame_axis = []

    for token in tokens:
        frame_axis.append(construct_input_frame(token, pos_encoding, n_pitch, n_velocity, frame_bias=frame_bias))

    return torch.stack(frame_axis, dim=0)

def construct_output_mask(tokens, n_pitch, n_velocity):
    '''
    An additive mask for the model's output (logits) to prevent the model from predicting invalid tokens.

    The first token must be pitch or next_frame.
    The next token of pitch must be velocity.
    The next token of next_frame can be pitch or next_frame.
    The next token of velocity must be pitch or next_frame.

    Accroding to the above rule, we can construct a mask as a prior on the model's prediction.
    '''

    mask = torch.zeros(len(tokens), n_pitch + n_velocity + 1)
    # fill with -inf
    mask = mask - 1e7

    mask[0, :n_pitch] = 0
    mask[0, n_pitch+n_velocity] = 0

    for i in range(len(tokens)-1):
        # output shape: Output: [pitch(n_pitch), velocity(n_velocity), next_frame(1)]
        token = tokens[i]

        if token['type'] == 'pitch':
            #enable velocity
            mask[i+1, n_pitch:n_pitch+n_velocity] = 0
        if token['type'] == 'velocity':
            #enable pitch or next_frame
            mask[i+1, :n_pitch] = 0
            mask[i+1, n_pitch+n_velocity] = 0
        if token['type'] == 'next_frame':
            #enable pitch or next_frame
            mask[i+1, :n_pitch] = 0
            mask[i+1, n_pitch+n_velocity] = 0

    return mask

def construct_target(tokens, n_pitch, n_velocity):
    res = []
    for i, token in enumerate(tokens):
        if token['type'] == 'pitch':
            res.append(token['value'])
        elif token['type'] == 'velocity':
            res.append(n_pitch + token['value'])
        elif token['type'] == 'next_frame':
            res.append(n_pitch + n_velocity)
        elif token['type'] == 'pad':
            res.append(-100) # -100 is the ignore index
        else:
            raise ValueError(f"Unknown token type: {token['type']}")

    return torch.tensor(res, dtype=torch.long)

pos_encoding = torch.cat([
    binary_positional_encoding(512,9),
    sinusoidal_positional_encoding(512, 31)
], dim=1)

class TokenizedPianoRollDataset(Dataset):
    '''
    Input: [pitch(n_pitch), velocity(n_velocity), next_frame(1), start(1), pos, target_pos]
    Output: [pitch(n_pitch), velocity(n_velocity), next_frame(1)]
    '''
    def __init__(self, path:str, pos_encoding:torch.Tensor, segment_length:int, hop_len:int, seq_len:int, n_pitch:int, n_velocity:int):
        self.ds = PianoRollDataset(path, segment_len=segment_length, hop_len=hop_len)
        self.pos_encoding = pos_encoding
        self.seq_len = seq_len
        self.n_pitch = n_pitch
        self.n_velocity = n_velocity
        self.segment_length = segment_length

        #self.tokens = []
        #for idx in range(len(self.ds)):
        #    self.tokens.append(tokenize(self.ds.get_piano_roll(idx), n_velocity=self.n_velocity, duration=self.segment_length, seq_len=self.seq_len))

    def __len__(self):
        return len(self.ds)

    def __getitem__(self, idx):
        #tokens = self.tokens[idx]

        pr = self.ds.get_piano_roll(idx)
        tokens = tokenize(pr, n_velocity=self.n_velocity, duration=self.segment_length, seq_len=self.seq_len)

        tokens_without_start = tokens[1:]

        # the last token is not needed to be an input
        input = construct_input_tensor(tokens[:-1], pos_encoding=self.pos_encoding, n_pitch=self.n_pitch, n_velocity=self.n_velocity)
        target = construct_target(tokens_without_start, n_pitch=self.n_pitch, n_velocity=self.n_velocity)
        output_mask = construct_output_mask(tokens_without_start, n_pitch=self.n_pitch, n_velocity=self.n_velocity)
        return {'input':input, 'target':target, 'output_mask':output_mask}
    
    def get_loss_weight(self):
        '''
        The loss weight for each token.
        '''
        res = torch.ones(self.n_pitch + self.n_velocity + 1)
        res[self.n_pitch + self.n_velocity] = 0.05 # next_frame is too common so we need to reduce its weight


In [4]:
ds = TokenizedPianoRollDataset('../dev_cwd/_data/gr_resource/download/music/pop_piano', pos_encoding, 512, 512, 1400, 88, 32)
dl = DataLoader(ds,batch_size=8, shuffle=True, num_workers=8)

Creating dataset segment_len = 512
Created dataset with 17141 data points from 2570 pieces


In [9]:
from torch import nn
from torch.optim import Adam
# input: B, 350, 202
# output: B, 350, 121

class PianoRollGenerator(nn.Module):
    def __init__(self):
        super().__init__()
        self.in_linear = nn.Linear(200, 256)
        self.transformer = nn.TransformerEncoder(nn.TransformerEncoderLayer(d_model=256, nhead=8, dim_feedforward=1024, batch_first=True), num_layers=6)
        self.out_linear = nn.Linear(256, 121)

    def forward(self, x):
        x = self.in_linear(x)
        x = self.transformer(x, mask = nn.Transformer.generate_square_subsequent_mask(x.shape[1]).to(x.device), is_causal = True)
        x = self.out_linear(x)
        return x
        
model = PianoRollGenerator()

crit = nn.CrossEntropyLoss()

opt = Adam(model.parameters(), lr=1e-4)

/root/miniconda3/envs/gr/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [46]:

import random
from grapycal_audio.pianoroll import Note

def top_k(logits:torch.Tensor, k):
    values, indices = logits.topk(k)
    probs = torch.softmax(values, dim=0)
    selected = torch.multinomial(probs, 1)
    return indices[selected]

def decode(logits, last_token, n_pitch, n_velocity):
    frame = last_token['next_frame']

    if last_token['type'] in ['start', 'velocity', 'next_frame']:
        logits[n_pitch:n_pitch+n_velocity] = - torch.inf
        max_idx = top_k(logits, 15).item()
        if max_idx < n_pitch:
            return {'type':'pitch', 'value':max_idx, 'frame':frame, 'next_frame':frame}
        elif max_idx == n_pitch + n_velocity:
            return {'type':'next_frame', 'frame':frame, 'next_frame':frame+1}
        else:
            raise ValueError(f"Invalid index: {max_idx}")
        
    elif last_token['type'] == 'pitch':
        logits[:n_pitch] = -torch.inf
        logits[n_pitch+n_velocity] = -torch.inf
        max_idx = top_k(logits, 15).item()
        return {'type':'velocity', 'value':max_idx - n_pitch, 'frame':frame, 'next_frame':frame}
    else:
        raise ValueError(f"Unknown token type: {last_token['type']}")
    
def token_to_pianoroll(tokens):
    notes = []
    frame = 0
    last_pitch = None
    for token in tokens:
        if token['type'] == 'start':
            continue
        if token['type'] == 'pitch':
            last_pitch = token['value']
        if token['type'] == 'velocity':
            notes.append(Note(onset=frame, pitch=last_pitch+21, velocity=int(token['value']*(128/32))))
        if token['type'] == 'next_frame':
            frame += 1
    return PianoRoll(notes)
    
# logits = out[0].detach().cpu()

# n_pitch = 88
# n_velocity = 32
# last_token = {'type':'start', 'frame':0, 'next_frame':0}
# tokens = []
# for frame_logits in logits:
#     decoded = decode(frame_logits, last_token, n_pitch, n_velocity)
#     tokens.append(decoded)
#     last_token = decoded
def inference(file_path:str, max_duration:int, max_length:int, prompt: list[dict]|None=None):
    model.eval()
    n_pitch = 88
    n_velocity = 32
    if prompt is None:
        tokens = [{'type':'start', 'frame':0, 'next_frame':0}]
    else:
        tokens = prompt
    
    while tokens[-1]['next_frame'] < max_duration and len(tokens) < max_length:
        input = construct_input_tensor(tokens, pos_encoding=pos_encoding, n_pitch=n_pitch, n_velocity=n_velocity).unsqueeze(0)
        input = input.to(device)
        logits = model(input).squeeze(0)[-1].detach().cpu()
        decoded = decode(logits, tokens[-1], n_pitch, n_velocity)
        tokens.append(decoded)

    token_to_pianoroll(tokens).to_midi(file_path)


In [15]:
# train
import time
from tqdm import tqdm


model.to(device)
crit.to(device)

model.train()

for epoch in range(100):
    tq = tqdm(dl)
    for i, batch in enumerate(tq):
        batch = {k:v.to(device) for k,v in batch.items()}
        opt.zero_grad()
        out = model(batch['input'])
        loss = crit((out+batch['output_mask']).transpose(1,2), batch['target'])
        loss.backward()
        opt.step()
        if i % 100 == 0:
            # print the loss to tqdm
            #temp = torch.cuda.temperature()
            temp = 0
            tq.set_postfix(batch = i, loss= loss.item(), gpu_temp=temp)

            if temp > 65:
                print("GPU temperature is too high. Slowin down.", temp)
                time.sleep(0.1)
        
                    
        if torch.isnan(loss):
            raise ValueError("Loss is NaN")
    
    if epoch % 10 == 0:
        inference(f'./output_{epoch}_{i}.mid')
        torch.save(model.state_dict(), f'./model_{epoch}.pth')
        torch.save(opt.state_dict(), f'./opt_{epoch}.pth')
    



100%|██████████| 2143/2143 [01:34<00:00, 22.78it/s, batch=2100, gpu_temp=0, loss=0.836]


In [49]:
inference('free2108252.mid',tokenize(PianoRoll.from_midi('free210825_2_C.mid').random_slice(128), n_velocity=32))

IndexError: index 512 is out of bounds for dimension 0 with size 512

In [21]:
inference('free2108252.mid',tokenize(PianoRoll.from_midi('free210825_2_C.mid').random_slice(128), n_velocity=32))

{'type': 'next_frame', 'frame': 78, 'next_frame': 79}

In [42]:
sum(p.numel() for p in model.parameters())

4821113

In [31]:
tokenize(PianoRoll.from_midi('free210825_2_C.mid').random_slice(128), n_velocity=32)[-20:]

[{'type': 'velocity', 'frame': 116, 'value': 14, 'next_frame': 116},
 {'type': 'pitch', 'frame': 116, 'value': 48, 'next_frame': 116},
 {'type': 'velocity', 'frame': 116, 'value': 23, 'next_frame': 116},
 {'type': 'next_frame', 'frame': 116, 'next_frame': 117},
 {'type': 'next_frame', 'frame': 117, 'next_frame': 118},
 {'type': 'next_frame', 'frame': 118, 'next_frame': 119},
 {'type': 'next_frame', 'frame': 119, 'next_frame': 120},
 {'type': 'pitch', 'frame': 120, 'value': 38, 'next_frame': 120},
 {'type': 'velocity', 'frame': 120, 'value': 22, 'next_frame': 120},
 {'type': 'next_frame', 'frame': 120, 'next_frame': 121},
 {'type': 'next_frame', 'frame': 121, 'next_frame': 122},
 {'type': 'next_frame', 'frame': 122, 'next_frame': 123},
 {'type': 'next_frame', 'frame': 123, 'next_frame': 124},
 {'type': 'pitch', 'frame': 124, 'value': 29, 'next_frame': 124},
 {'type': 'velocity', 'frame': 124, 'value': 20, 'next_frame': 124},
 {'type': 'pitch', 'frame': 124, 'value': 50, 'next_frame': 12

In [29]:
import torch
torch.cuda.is_available()

In [7]:
from torch.utils.data import DataLoader, Dataset
ds = [1,2,3,4,5,36,4,1]
dl = DataLoader(ds, batch_size=2, shuffle=True, num_workers=2)
for b in dl:
    print(b)

tensor([4, 4])
tensor([ 2, 36])
tensor([5, 1])
tensor([3, 1])


In [31]:
scale = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B']
quality = {
    '': [0,4,7],
    'm': [0,3,7],
    '7': [0,4,7,10],
    'm7': [0,3,7,10],
}
chord_to_chroma = {}
for i, s in enumerate(scale):
    for q in quality:
        chord_to_chroma[f"{s}{q}"] = [(x+i)%12 for x in quality[q]]

def chroma_to_chord(query):
    scores = {}
    for chord, chroma in chord_to_chroma.items():
        score = 0
        for i in chroma:
            score += query[i]
        scores[chord] = score
    print(scores)
    argmax = max(scores, key=scores.get)
    return argmax

In [7]:
ds.ds.get_piano_roll(4884).get_polyphony()

[2.3333333333333335,
 1.0,
 3.3333333333333335,
 1.6666666666666667,
 2.3333333333333335,
 1.0,
 2.0,
 1.0,
 2.0,
 2.0,
 1.3333333333333333,
 1.0,
 2.0,
 1.3333333333333333,
 1.3333333333333333,
 1.6666666666666667]

In [8]:
ds.ds.get_piano_roll(4884).to_midi('test.mid')

ticks per beat: 480
max tick: 0
tempo changes: 1
time sig: 0
key sig: 0
markers: 0
lyrics: False
instruments: 1

In [12]:
def get_max_n(array, n):
    """
    Get the indices of the n largest elements in an array
    """
    result = []
    for i in range(n):
        if i >= len(array):
            break
        max_index = np.argmax(array)
        result.append(max_index)
        array[max_index] = 0
    return result


In [13]:
get_max_n([1,2,3,4,5,6,7,8,9,10], 3)


NameError: name 'np' is not defined